version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "trentm"
    groups:
      otel:
        patterns:
        - "@opentelemetry/*"
